################################################################################
# SPDX-FileCopyrightText: 2019 SAP
#                                                                              #
# SPDX-License-Identifier: Apache-2.0
################################################################################

---
driver:
  name: docker

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 12

verifier:
  name: inspec

platforms:
- name: ubuntu

suites:
- name: default
  run_list:
    - recipe[sapohai]
  verifier:
    inspec_tests:
      - test/smoke/default
